// <auto-generated />
using System;
using B2B.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace B2B.Infrastructure.Migrations
{
    [DbContext(typeof(B2BDbContext))]
    [Migration("20260525195723_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("B2B.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Ordering")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("ordering");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_categories_parent_active")
                        .HasFilter("deleted = false");

                    b.HasIndex("ParentId", "Ordering")
                        .HasDatabaseName("ix_categories_parent_ordering");

                    b.ToTable("categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_categories_no_self_parent", "parent_id IS NULL OR parent_id <> id");

                            t.HasCheckConstraint("ck_categories_ordering_non_negative", "ordering >= 0");
                        });
                });

            modelBuilder.Entity("B2B.Domain.Images.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("entity_type");

                    b.Property<int>("Ordering")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("ordering");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId", "Ordering")
                        .HasDatabaseName("ix_images_owner");

                    b.ToTable("images", null, t =>
                        {
                            t.HasCheckConstraint("ck_images_entity_type_valid", "entity_type IN ('product', 'sku')");

                            t.HasCheckConstraint("ck_images_ordering_non_negative", "ordering >= 0");
                        });
                });

            modelBuilder.Entity("B2B.Domain.Invoices.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("accepted_at");

                    b.Property<Guid?>("AcceptedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_invoices_status_created")
                        .HasFilter("status = 'Created'");

                    b.HasIndex("SellerId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_invoices_seller_status_created");

                    b.ToTable("invoices", null, t =>
                        {
                            t.HasCheckConstraint("ck_invoices_accepted_at_consistency", "(status = 'Created' AND accepted_at IS NULL) OR (status <> 'Created')");
                        });
                });

            modelBuilder.Entity("B2B.Domain.Invoices.InvoiceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AcceptedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("accepted_quantity");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.HasKey("Id");

                    b.HasIndex("SkuId")
                        .HasDatabaseName("ix_invoice_items_sku");

                    b.HasIndex("InvoiceId", "SkuId")
                        .IsUnique()
                        .HasDatabaseName("ux_invoice_items_invoice_sku");

                    b.ToTable("invoice_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_invoice_items_accepted_quantity_valid", "accepted_quantity IS NULL OR (accepted_quantity >= 0 AND accepted_quantity <= quantity)");

                            t.HasCheckConstraint("ck_invoice_items_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("B2B.Domain.Products.FieldReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("field_name");

                    b.Property<int>("ModerationRound")
                        .HasColumnType("integer")
                        .HasColumnName("moderation_round");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("reported_at");

                    b.Property<Guid?>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_field_reports_product");

                    b.HasIndex("SkuId")
                        .HasDatabaseName("ix_field_reports_sku");

                    b.ToTable("field_reports", null, t =>
                        {
                            t.HasCheckConstraint("ck_field_reports_round_positive", "moderation_round > 0");
                        });
                });

            modelBuilder.Entity("B2B.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("description");

                    b.Property<int>("ModerationRound")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("moderation_round");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category");

                    b.HasIndex("SellerId", "Status")
                        .HasDatabaseName("ix_products_seller_status");

                    b.HasIndex("Status", "Deleted")
                        .HasDatabaseName("ix_products_status_deleted");

                    b.ToTable("product", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_moderation_round_non_negative", "moderation_round >= 0");
                        });
                });

            modelBuilder.Entity("B2B.Domain.Sellers.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<bool>("Revoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("revoked");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("ix_refresh_tokens_seller");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_hash");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("B2B.Domain.Sellers.Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("inn");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("middle_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_sellers_email")
                        .HasFilter("deleted = false");

                    b.ToTable("sellers", (string)null);
                });

            modelBuilder.Entity("B2B.Domain.Skus.Sku", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActiveQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("active_quantity");

                    b.Property<string>("Article")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("article");

                    b.Property<int?>("CostPrice")
                        .HasColumnType("integer")
                        .HasColumnName("cost_price");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<int>("Discount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("discount");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("ReservedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reserved_quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_skus_product_active")
                        .HasFilter("deleted = false");

                    b.ToTable("skus", null, t =>
                        {
                            t.HasCheckConstraint("ck_skus_active_quantity_non_negative", "active_quantity >= 0");

                            t.HasCheckConstraint("ck_skus_cost_price_valid", "cost_price IS NULL OR cost_price >= 0");

                            t.HasCheckConstraint("ck_skus_discount_valid", "discount >= 0 AND (price = 0 OR discount < price)");

                            t.HasCheckConstraint("ck_skus_price_non_negative", "price >= 0");

                            t.HasCheckConstraint("ck_skus_reserved_quantity_non_negative", "reserved_quantity >= 0");
                        });
                });

            modelBuilder.Entity("B2B.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("message_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_on_utc");

                    b.Property<DateTime>("ReceivedOnUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("received_on_utc");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.HasKey("IdempotencyKey");

                    b.HasIndex("ReceivedOnUtc")
                        .HasDatabaseName("ix_inbox_unprocessed")
                        .HasFilter("processed_on_utc IS NULL");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("B2B.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("aggregate_type");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("destination");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_on_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_on_utc");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.HasKey("Id");

                    b.HasIndex("OccurredOnUtc")
                        .HasDatabaseName("ix_outbox_unprocessed")
                        .HasFilter("processed_on_utc IS NULL");

                    b.HasIndex("AggregateType", "AggregateId")
                        .HasDatabaseName("ix_outbox_aggregate");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("B2B.Domain.Categories.Category", b =>
                {
                    b.HasOne("B2B.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("B2B.Domain.Invoices.InvoiceItem", b =>
                {
                    b.HasOne("B2B.Domain.Invoices.Invoice", null)
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("B2B.Domain.Products.FieldReport", b =>
                {
                    b.HasOne("B2B.Domain.Products.Product", null)
                        .WithMany("FieldReports")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("B2B.Domain.Products.Product", b =>
                {
                    b.OwnsOne("B2B.Domain.Products.BlockingReason", "BlockingReason", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Comment")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("blocking_reason_comment");

                            b1.Property<Guid>("ReasonId")
                                .HasColumnType("uuid")
                                .HasColumnName("blocking_reason_reason_id");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("blocking_reason_title");

                            b1.HasKey("ProductId");

                            b1.ToTable("product");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsMany("B2B.Domain.Products.ProductCharacteristic", "Characteristics", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("value");

                            b1.Property<Guid>("product_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("product_id");

                            b1.ToTable("product_characteristics", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("product_id");
                        });

                    b.Navigation("BlockingReason");

                    b.Navigation("Characteristics");
                });

            modelBuilder.Entity("B2B.Domain.Skus.Sku", b =>
                {
                    b.OwnsMany("B2B.Domain.Skus.SkuCharacteristic", "Characteristics", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("value");

                            b1.Property<Guid>("sku_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("sku_id");

                            b1.ToTable("sku_characteristics", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("sku_id");
                        });

                    b.Navigation("Characteristics");
                });

            modelBuilder.Entity("B2B.Domain.Invoices.Invoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("B2B.Domain.Products.Product", b =>
                {
                    b.Navigation("FieldReports");
                });
#pragma warning restore 612, 618
        }
    }
}
